### PR TITLE
Add `.once(type)` sugar method overload

### PR DESCRIPTION
**Pull request by addaleax**
It can be helpful to have a promise fulfilled when a certain event is emitted. This adds a simple `.promiseOnce(type)` wrapper around `.once(type)` which achieves that.

```js
emitter.promiseOnce('foo').then(() => console.log('foo!'));

emitter.emit('foo'); // writes "foo!" to the console
emitter.emit('foo'); // does nothing
```

I’m neither fully set on the method’s name nor on whether this should actually go into EventEmitter, but even though it’s just a short piece of code, I like it and I think it might belong here. :)

### CODE REVIEW

**Comment by yanickrochon** [comment]
So... attaching a handler invoked after *all* and *any* other handlers, right?

Because of the nature of Promises, I'm not sure that it can actually guarantee what you intended. For example, when you add another `once` (or `on`) after `promiseOnce`, then the last handler will not be executed after everything else...

**Comment by addaleax** [comment]
Mh, I’m not really talking about some relation between the `.promiseOnce` handler and the other handlers for a given event. It is just that the `.once(type, callback)` signature is precisely the kind of thing that Promises are supposed to simplify (an once-only invoked callback).

I guess my choice of words in “when a certain event is emitted” is not ideal, but I don’t mean that the promise would be fulfilled only after other handlers.

**Comment by addaleax** [comment]
What I’m talking about are use cases like this: If you want some code to execute when a certain event is fired for the first time, or you *know* that a certain event is only emitted once (e.g. the `end` event of `stream.Readable` instances), you can remove the nesting from
```js
stream.on('end', function() {
  // some code
});
```
and turn it into
```js
stream.promiseOnce('end').then(function() {
  // some code
});
```
In this example, of course, nothing is gained, but once the code becomes a bit more complex (e.g. handling 2 streams with nontrivial interactions between them), the usual upsides of using Promises over callbacks are there.

**Comment by yanickrochon** [comment]
Right, I get it now. So, the promise returned should only be resolved when the event is emitter. As opposed to right now, `emitter.on` is resolved after `newListener`, etc. And since you can only resolve a promise once, this only applies to `once`. (Just came back from Holidays, still a little fuzzy.)

Ok, yeah, I'm not too yay on the name `promiseOnce`. Will think about this....

**Comment by addaleax** [comment]
Exactly, yes :) It’s more or less another way to spell out `.once(…)`. One possible alternative for the method name would be to make `.once(type)` with only one argument return a Promise, so that you can write `events.once(type).then(function() { …` instead of `events.once(type, function() { …`. Maybe that’s better?

**Comment by yanickrochon** [comment]
Yes, I think it would be more intuitive, and I really don't mind method overloading.

In the `once` method, simply check `if (arguments.length === 1)` and add the implementation there. `else` use the current (default) implementation. All test cases should be fine, and adding new ones needs only checking calling `once` with a single argument.

Then, you can [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your commits for a cleaner PR.

**Comment by addaleax** [comment]
Okay, I updated everything as requested :)

**Comment by addaleax** [comment]
Fixed again, sorry :)

**Comment by yanickrochon** [comment]
Excellent! Thank!

**Pull request merged**
